### ISSUE TITLE
group-tag-Set action is failing

### ISSUE THREAD

**Issue by nikmat1** [swaschkut/pan-os-php#14]
I get an error when I try to set a group tag. This does not seem to depend on a filter. Here is an example command I run:

pan-os-php type=rule in=api://_panorama address_   location=_device group name_ 'filter=!(group-tag is.set) and (rule is.prerule)' 'actions=group-tag-Set:_tag_'

When executed with action display - it executes successfully, listing correct rules from the device group. However, when the action is swapped to the **group-tag-Set**, I get the error as follows:

processing ruleset 'PanoramaConf: / DeviceGroup:_device group name_ / RuleStore:Security' that holds 301 rules
   - object '_rule name_'  passing through Action='group-tag-Set' Args: Group-Tag=_tag_,
PHP Fatal error:  Uncaught Error: Call to undefined method GroupTagRuleContainer::removeReference() in /tools/pan-os-php/lib/rule-classes/RuleWithGroupTag.php:119

pan-os-php version
 - PAN-OS-PHP version: 2.1.23 [UNIX]
 - /tools/pan-os-php/utils
 - PHP version: 8.1.2-1ubuntu2.14

(running in Docker under WSL in Windows 10)

**Comment by swaschkut** [comment]
Thanks for finding this Bug and sharing it with me.

I already tried to fix it just in time,
but it looks like that this is a longer part than just a few minutes.

Please be patient, I will fix this at the beginning of June.
Thanks for your understanding.

**Comment by nikmat1** [comment]
Thank you, Sven.

Can you tell me in which version this functionality stopped working? I know for a fact that this action worked well before but since I always use the "latest" tag, it's now difficult to figure out which version I'd need to roll back to to recover this particular function.

(I have a lot of tagging to do hence the question)

**Comment by swaschkut** [comment]
you are totally right,

with version 2.1.16 I did some changes.
your stuff was working from version 2.0.75 including 2.1.15;

docker run --name panosphp --rm -v ${PWD}:/share -it swaschkut/pan-os-php:2.1.15

should still work for you.
I am closure to the real issue and will fix it this week

**Comment by swaschkut** [comment]
a fixed version is now available:

docker run --name panosphp --rm -v ${PWD}:/share -it swaschkut/pan-os-php:develop

it will be published soon in version 2.1.24

**Comment by swaschkut** [comment]
bugfix published with #16
