### ISSUE TITLE
Feature request: show Group Rules By Tag in exportToExcel output

### ISSUE THREAD

**Issue by bethatasitmay** [swaschkut/pan-os-php#20]
Hi

### Is your feature request related to a problem?

It's not a problem as such - it would occasionally be nice to have the Group Rules By Tag field in the output of the exportToExcel action.

### Describe the solution you'd like

Please include the Group Rules By Tag field in the output of the exportToExcel action (probably immediately to the right of the column for tags).

### Describe alternatives you've considered

N/A

### Additional context

I was going to a scripted change to the Group Rules By Tag (action group-tag-Set) for a set of rules and wanted to capture what the originals were.

This is a nice-to-have so little to no priority.  I don't use this action hardly at all (yesterday was the first time since the action was introduced), but I may want to use it again in the future, so it would be nice to be able to capture what the rules looked like prior to making large changes.

Thanks for the consideration!

**Comment by swaschkut** [comment]
this is now available in develop Container which is git repository:

https://github.com/swaschkut/pan-os-php/blob/develop_2-1-X

it will be included in next latest release of the main repository shortly.


Please validate

**Comment by swaschkut** [comment]
added with version 2.1.25
#21

**Comment by bethatasitmay** [comment]
Works perfectly - thanks!
