### ISSUE TITLE
Bug-08072024-1 Clone action adds "0" at the end of user defined string

### ISSUE THREAD

**Issue by nexusops** [swaschkut/pan-os-php#22]
## Describe the bug

Clone action from type=rule adds "0" at the end of user defined suffix

## Expected behavior

The suffix added to the cloned rules should match the string defined by the user

## Current behavior

"0" is added by PAN-OS-PHP at the end of the defined string

## Possible solution

Prevent PAN-OS-PHP from adding "0" at the end of the suffix

## Steps to reproduce

1. Run any of these commands
`pan-os-php type=rule in=config.xml location=any 'actions=clone:yes,-This-is-a-suffix' out=config-suffix-test-1.xml`
`pan-os-php type=rule in=config.xml location=any 'actions=clone:yes,"-This-is-a-suffix"' out=config-suffix-test-2.xml`
`pan-os-php type=rule in=config.xml location=any 'actions=clone:yes,'-This-is-a-suffix'' out=config-suffix-test-3.xml`

![image](https://github.com/swaschkut/pan-os-php/assets/20437364/2d12388e-3ade-4465-afe4-ea30032fe75c)

- Version used: 2.1.25

**Comment by swaschkut** [comment]
thanks for sharing this information.

please validate the develop repository:
https://github.com/swaschkut/pan-os-php/tree/develop_2-1-X

or the develop Docker container:
docker pull swaschkut/pan-os-php:develop

**Comment by nexusops** [comment]
Hi Sven,
confirmed as fixed in 2.1.26 version. Thanks for fixing this so quickly :) 

![image](https://github.com/swaschkut/pan-os-php/assets/20437364/5ad8a4ef-6f20-4feb-997b-e05fd03d53c1)
